version: "3.9"

# main part
services:
  db:
    container_name: db
    image: postgres:latest
    command:
      - "postgres"
      - "-c"
      - "max_connections=250"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=600s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    volumes:
      - .:/var/lib/postgresql/data
    environment:
      TZ: Europe/Moscow
      POSTGRES_DB: taskmanager
      POSTGRES_USER: taskmanager
      POSTGRES_PASSWORD: taskmanager
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    restart: unless-stopped

  # rabbit:
  #   image: rabbitmq:3-management-alpine
  #   container_name: rabbit
  #   restart: always
  #   environment:
  #     TZ: Europe/Moscow
  #   <<: *log-tmpl
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   volumes:
  #     - ./data/rabbit:/var/lib/rabbitmq
